// src\admin\adminMocks.ts

import {
  AdminProduct,
  Customer,
  Order,
  PodSettings,
  SyncLog,
  AdminUser,
  StoreSettings,
} from "./adminTypes";

const IMG =
  "https://cdn.pixabay.com/photo/2026/01/26/22/44/cat-10089737_1280.png";

export const MOCK_PRODUCTS: AdminProduct[] = [
  {
    id: "prod-rio-carnival-tshirt",
    isActive: true,
    title: "T-Shirt Rio Carnival Neon Edition 2026",
    brand: "INSTAWEAR",
    description: "T-shirt premium en coton bio célébrant le Carnaval de Rio.",
    fullDescription:
      "• Coton 100% biologique peigné (180 g/m²)\n• Impression numérique HD",
    image: IMG,
    gallery: [IMG, IMG],
    price: 29.99,
    originalPrice: 45.0,
    inStock: true,
    stockQuantity: 50,
    colors: ["#00FFFF", "#FF00FF", "#1E1E1E", "#FFFFFF"],
    colorNames: [
      "Cyan Électrique",
      "Rose Samba",
      "Noir Anthracite",
      "Blanc Pur",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    sizeSurcharge: { XXL: 2 },
    category: "tshirt",
    eventType: "culture",
    style: "street",
    material: "coton-bio",
    tags: ["Carnaval", "Rio", "Neon", "Samba"],
    isBestSeller: true,
    isLimitedTime: true,
    dealActive: false,
    affiliateMode: false,
    ratings: { score: 4.8, count: 124 },
    boughtLastMonth: 850,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-05-15T14:30:00Z",
  },
  {
    id: "prod-ucl-champions-hoodie",
    isActive: true,
    title: "Hoodie Retro UCL Champions Finals 2026",
    brand: "INSTAWEAR",
    description:
      "Sweat à capuche premium ultra-confort commémorant la finale UCL.",
    fullDescription: "• 85% coton bio peigné, 15% polyester recyclé (350 g/m²)",
    image: IMG,
    gallery: [IMG],
    price: 54.99,
    originalPrice: 79.99,
    inStock: true,
    stockQuantity: 35,
    colors: ["#0F172A", "#475569", "#FFFFFF"],
    colorNames: ["Bleu Minuit", "Gris Athlétique", "Blanc Pur"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    sizeSurcharge: { XXL: 2 },
    category: "hoodie",
    eventType: "sport",
    style: "cozy",
    material: "polyester-recycle",
    tags: ["UCL", "Champions", "Football"],
    isBestSeller: true,
    isLimitedTime: false,
    dealActive: true,
    dealPrice: 44.99,
    dealEndsAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    affiliateMode: false,
    ratings: { score: 4.9, count: 452 },
    boughtLastMonth: 1420,
    externalProductId: "pfl-001",
    externalVariantId: "pfl-var-002",
    lastExternalSync: "2026-05-10T08:00:00Z",
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-05-18T11:00:00Z",
  },
  {
    id: "prod-halloween-glow-hoodie",
    isActive: false,
    title: "Hoodie Halloween Creepy Glow 2026",
    brand: "INSTAWEAR",
    description: "Sweat à capuche au design fluorescent pour Halloween.",
    fullDescription: "• Coupe confort avec emmanchures descendues (300 g/m²)",
    image: IMG,
    gallery: [IMG],
    price: 49.99,
    originalPrice: 69.99,
    inStock: true,
    stockQuantity: 20,
    colors: ["#EA580C", "#1E1E1E", "#4D7C0F"],
    colorNames: ["Orange Citrouille", "Noir Absolu", "Vert Toxique"],
    sizes: ["M", "L", "XL", "XXL"],
    category: "hoodie",
    eventType: "saisonnier",
    style: "cozy",
    material: "coton-bio",
    tags: ["Halloween", "Glow", "Saison"],
    isBestSeller: false,
    isLimitedTime: false,
    dealActive: false,
    affiliateMode: false,
    ratings: { score: 4.6, count: 68 },
    boughtLastMonth: 120,
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "prod-retro-olympics-cap",
    isActive: true,
    title: "Casquette Trucker Olympics Vintage 2026",
    brand: "INSTAWEAR",
    description: "Casquette rétro brodée aux couleurs olympiques.",
    image: IMG,
    gallery: [IMG],
    price: 19.99,
    originalPrice: 29.99,
    inStock: true,
    stockQuantity: 80,
    colors: ["#1E3A8A", "#B91C1C", "#15803D"],
    colorNames: ["Bleu Stadium", "Rouge Athlète", "Vert Olympique"],
    sizes: ["Unique (Réglable)"],
    category: "accessory",
    eventType: "sport",
    style: "retro",
    material: "polyester-recycle",
    tags: ["Olympics", "Casquette", "Sport"],
    isBestSeller: true,
    isLimitedTime: false,
    dealActive: false,
    affiliateMode: false,
    ratings: { score: 4.9, count: 320 },
    boughtLastMonth: 950,
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "prod-new-year-mug",
    isActive: true,
    title: "Mug Céramique Midnight Countdown 2026",
    brand: "INSTAWEAR",
    description: "Mug thermo-réactif révélant un feu d'artifice doré.",
    image: IMG,
    gallery: [IMG],
    price: 14.99,
    originalPrice: 19.99,
    inStock: false,
    stockQuantity: 0,
    colors: ["#000000", "#FFFFFF"],
    colorNames: ["Noir Minuit", "Blanc Pur"],
    sizes: ["Format Standard"],
    category: "mug",
    eventType: "saisonnier",
    style: "cute",
    material: "ceramique",
    tags: ["Nouvel An", "Mug", "Fêtes"],
    isBestSeller: false,
    isLimitedTime: false,
    dealActive: false,
    affiliateMode: false,
    ratings: { score: 4.5, count: 52 },
    boughtLastMonth: 180,
    createdAt: "2025-11-15T10:00:00Z",
    updatedAt: "2026-01-10T10:00:00Z",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    email: "camille.rousseau@email.fr",
    name: "Camille Rousseau",
    registrationDate: "2025-09-01T10:00:00Z",
    lastLoginDate: "2026-05-14T08:30:00Z",
  },
  {
    id: "cust-002",
    email: "marco.ferreira@email.fr",
    name: "Marco Ferreira",
    registrationDate: "2025-10-15T11:00:00Z",
    lastLoginDate: "2026-05-10T16:00:00Z",
  },
  {
    id: "cust-003",
    email: "sophie.marchetti@email.fr",
    name: "Sophie Marchetti",
    registrationDate: "2026-01-03T09:30:00Z",
    lastLoginDate: "2026-04-28T12:00:00Z",
  },
  {
    id: "cust-004",
    email: "antoine.delbos@email.fr",
    name: "Antoine Delbos",
    registrationDate: "2026-02-20T14:00:00Z",
    lastLoginDate: "2026-05-01T09:45:00Z",
  },
  {
    id: "cust-005",
    email: "lucie.martin@email.fr",
    name: "Lucie Martin",
    registrationDate: "2026-03-12T10:00:00Z",
    lastLoginDate: "2026-05-13T20:00:00Z",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-2026-0001",
    clientId: "cust-001",
    clientName: "Camille Rousseau",
    clientEmail: "camille.rousseau@email.fr",
    createdAt: new Date().toISOString(),
    status: "pending",
    totalAmount: 84.98,
    shippingCost: 0,
    shippingAddress: {
      fullName: "Camille Rousseau",
      address: "12 rue des Lilas",
      city: "Paris",
      zip: "75011",
      country: "FR",
      phone: "+33612345678",
    },
    notes: "Livraison rapide si possible",
    items: [
      {
        id: "item-001",
        orderId: "ORD-2026-0001",
        productId: "prod-rio-carnival-tshirt",
        productTitle: "T-Shirt Rio Carnival Neon Edition 2026",
        productImage: IMG,
        selectedColor: "#00FFFF",
        selectedSize: "M",
        quantity: 1,
        unitPrice: 29.99,
      },
      {
        id: "item-002",
        orderId: "ORD-2026-0001",
        productId: "prod-ucl-champions-hoodie",
        productTitle: "Hoodie Retro UCL Champions Finals 2026",
        productImage: IMG,
        selectedColor: "#0F172A",
        selectedSize: "L",
        quantity: 1,
        unitPrice: 54.99,
      },
    ],
  },
  {
    id: "ORD-2026-0002",
    clientId: "cust-002",
    clientName: "Marco Ferreira",
    clientEmail: "marco.ferreira@email.fr",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    status: "in_production",
    totalAmount: 29.99,
    shippingCost: 4.99,
    shippingAddress: {
      fullName: "Marco Ferreira",
      address: "5 avenue de la Gare",
      city: "Lyon",
      zip: "69001",
      country: "FR",
      phone: "+33698765432",
    },
    items: [
      {
        id: "item-003",
        orderId: "ORD-2026-0002",
        productId: "prod-rio-carnival-tshirt",
        productTitle: "T-Shirt Rio Carnival Neon Edition 2026",
        productImage: IMG,
        selectedColor: "#FF00FF",
        selectedSize: "XL",
        quantity: 1,
        unitPrice: 29.99,
      },
    ],
  },
  {
    id: "ORD-2026-0003",
    clientId: "cust-003",
    clientName: "Sophie Marchetti",
    clientEmail: "sophie.marchetti@email.fr",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: "shipped",
    totalAmount: 19.99,
    shippingCost: 0,
    shippingAddress: {
      fullName: "Sophie Marchetti",
      address: "8 cours Victor Hugo",
      city: "Bordeaux",
      zip: "33000",
      country: "FR",
      phone: "+33655443322",
    },
    items: [
      {
        id: "item-004",
        orderId: "ORD-2026-0003",
        productId: "prod-retro-olympics-cap",
        productTitle: "Casquette Trucker Olympics Vintage 2026",
        productImage: IMG,
        selectedColor: "#1E3A8A",
        selectedSize: "Unique (Réglable)",
        quantity: 1,
        unitPrice: 19.99,
      },
    ],
  },
  {
    id: "ORD-2026-0004",
    clientId: "cust-004",
    clientName: "Antoine Delbos",
    clientEmail: "antoine.delbos@email.fr",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    status: "delivered",
    totalAmount: 49.99,
    shippingCost: 4.99,
    shippingAddress: {
      fullName: "Antoine Delbos",
      address: "3 allée des Roses",
      city: "Toulouse",
      zip: "31000",
      country: "FR",
      phone: "+33677889900",
    },
    items: [
      {
        id: "item-005",
        orderId: "ORD-2026-0004",
        productId: "prod-halloween-glow-hoodie",
        productTitle: "Hoodie Halloween Creepy Glow 2026",
        productImage: IMG,
        selectedColor: "#EA580C",
        selectedSize: "L",
        quantity: 1,
        unitPrice: 49.99,
      },
    ],
  },
  {
    id: "ORD-2026-0005",
    clientId: "cust-005",
    clientName: "Lucie Martin",
    clientEmail: "lucie.martin@email.fr",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    status: "delivered",
    totalAmount: 44.98,
    shippingCost: 0,
    shippingAddress: {
      fullName: "Lucie Martin",
      address: "22 rue du Commerce",
      city: "Nantes",
      zip: "44000",
      country: "FR",
      phone: "+33611223344",
    },
    items: [
      {
        id: "item-006",
        orderId: "ORD-2026-0005",
        productId: "prod-rio-carnival-tshirt",
        productTitle: "T-Shirt Rio Carnival Neon Edition 2026",
        productImage: IMG,
        selectedColor: "#1E1E1E",
        selectedSize: "S",
        quantity: 1,
        unitPrice: 29.99,
      },
      {
        id: "item-007",
        orderId: "ORD-2026-0005",
        productId: "prod-new-year-mug",
        productTitle: "Mug Céramique Midnight Countdown 2026",
        productImage: IMG,
        selectedColor: "#000000",
        selectedSize: "Format Standard",
        quantity: 1,
        unitPrice: 14.99,
      },
    ],
  },
];

export const MOCK_POD_SETTINGS: PodSettings = {
  id: "pod-main",
  apiKey: "",
  storeId: "",
  storeName: "InstaWear Boutique",
  isConnected: false,
  productsSyncedCount: 0,
  syncStatus: "idle",
};

export const MOCK_SYNC_LOGS: SyncLog[] = [
  {
    id: "log-001",
    syncDate: new Date(Date.now() - 86400000).toISOString(),
    status: "success",
    message: "5 produits synchronisés avec succès.",
    duration: 1243,
  },
  {
    id: "log-002",
    syncDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: "partial",
    message: "3/5 produits synchronisés. 2 erreurs de variantes.",
    duration: 2100,
  },
  {
    id: "log-003",
    syncDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    status: "error",
    message: "Clé API invalide ou expirée.",
    duration: 450,
  },
];

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: "admin-001",
    email: "admin@instawear.shop",
    role: "super_admin",
    createdAt: "2025-01-01T00:00:00Z",
    lastLoginDate: new Date().toISOString(),
  },
  {
    id: "admin-002",
    email: "editor@instawear.shop",
    role: "editor",
    createdAt: "2025-06-01T00:00:00Z",
    lastLoginDate: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const MOCK_STORE_SETTINGS: StoreSettings = {
  storeName: "InstaWear",
  currency: "EUR",
  country: "FR",
  freeShippingThreshold: 35,
  shippingCost: 4.99,
  shippingDelay: "3-5 jours ouvrés",
  globalCountdownEnd: new Date(Date.now() + 86400000 * 5).toISOString(),
};
